### PR TITLE
Fix and simplify a set cleaning logic

### PR DESCRIPTION
**Pull request by Zizitto**
Hot-fix for #1041

### CODE REVIEW

**Comment by kkoomen** [comment]
@Zizitto v0.2.2 has been published  to NPM. Please check again and let me know.

Also, do you know what the actual problem was? how can this be reproduced? In order for me to write tests for this scenario, I need to know the actual problem.

**Comment by Zizitto** [comment]
There were wrong parameters passed to "srem" command.
The first parameter should be a key, but i`ve passed a list of members there, by mistake.

**Comment by Zizitto** [comment]
Checked 0.2.2, issue gone.

**Comment by Zizitto** [comment]
Many thanks for the fast resolving.

**Comment by kkoomen** [comment]
> Many thanks for the fast resolving.

Many thanks for contributing!

**Pull request merged**
